# -*- coding: utf-8 -*-
"""KNN_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ct6ZlIjML3wzIse0_eg6FryO5hs2CeHJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("health_risk_classification.csv")
df.head()

df.info()

df.describe()

sns.scatterplot(x=df["blood_pressure_variation"], y=df["activity_level_index"], hue=df["high_risk_flag"])

df.corr()

"""Veriye bakınca tansiyondaki dalgalanma arttıkça riskin arttığını yorumlayabiliriz."""

df["high_risk_flag"].value_counts()

"""Datanın balanced olduğunu gözlemledik"""

X = df.drop("high_risk_flag", axis=1)
y = df["high_risk_flag"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=15)

sns.boxenplot(df)
plt.show()

"""Scale edilmiş bir data olduğu için scaler kullanmasak da olur fakat notlarımızın içinde bulunması açısından kullanalım."""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3, algorithm="auto", weights="uniform")
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("confusion_matrix:\n", confusion_matrix(y_pred, y_test))
print("accuracy_score: ", accuracy_score(y_pred, y_test))
print("classification_report:\n", classification_report(y_pred, y_test))